### ISSUE TITLE
Rubygems

### ISSUE THREAD

**Issue by petems** [achiurizo/mplayer-ruby#1]
Hi @achiu!

Do you mind adding me to the owners on Rubygems?

If not I'll make a fork gem version and push that up for the latest merged changes :+1: 

Thanks!

**Comment by achiurizo** [comment]
@petems yeah sure thing. email to use?

**Comment by petems** [comment]
p. morsou at gmail dot com :+1:

**Comment by achiurizo** [comment]
done!
